# Generated by Django 4.2.2 on 2023-07-06 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='update_at',
        ),
    ]
